Adds bootstrap errors for impulse responses in VAR environment
statsmodels/statsmodels pull request #6769
Opened 2020-06-01 12:40 UTC by evivanov

- [ ] closes #xxxx
- [ ] tests added / passed. 
- [ ] code/documentation is well formatted.  
- [ ] properly formatted commit message. See 
      [NumPy's guide](https://docs.scipy.org/doc/numpy-1.15.1/dev/gitwash/development_workflow.html#writing-the-commit-message). 

<details>

**Notes**:

* It is essential that you add a test when making code changes. Tests are not 
  needed for doc changes.
* When adding a new function, test values should usually be verified in another package (e.g., R/SAS/Stata).
* When fixing a bug, you must add a test that would produce the bug in master and
  then show that it is fixed with the new code.
* New code additions must be well formatted. Changes should pass flake8. If on Linux or OSX, you can
  verify you changes are well formatted by running 
  ```
  git diff upstream/master -u -- "*.py" | flake8 --diff --isolated
  ```
  assuming `flake8` is installed. This command is also available on Windows 
  using the Windows System for Linux once `flake8` is installed in the 
  local Linux environment. While passing this test is not required, it is good practice and it help 
  improve code quality in `statsmodels`.
* Docstring additions must render correctly, including escapes and LaTeX.

</details>

2020-06-01 12:40 UTC, pep8speaks commented
Hello @evivanov! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`statsmodels/tsa/vector_ar/irf.py`](https://github.com/statsmodels/statsmodels/blob/faa2b48553f2c50421507dca5d20a1bc624b3077/statsmodels/tsa/vector_ar/irf.py):

> [Line 511:1](https://github.com/statsmodels/statsmodels/blob/faa2b48553f2c50421507dca5d20a1bc624b3077/statsmodels/tsa/vector_ar/irf.py#L511): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 515:36](https://github.com/statsmodels/statsmodels/blob/faa2b48553f2c50421507dca5d20a1bc624b3077/statsmodels/tsa/vector_ar/irf.py#L515): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 541:1](https://github.com/statsmodels/statsmodels/blob/faa2b48553f2c50421507dca5d20a1bc624b3077/statsmodels/tsa/vector_ar/irf.py#L541): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 557:1](https://github.com/statsmodels/statsmodels/blob/faa2b48553f2c50421507dca5d20a1bc624b3077/statsmodels/tsa/vector_ar/irf.py#L557): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 558:1](https://github.com/statsmodels/statsmodels/blob/faa2b48553f2c50421507dca5d20a1bc624b3077/statsmodels/tsa/vector_ar/irf.py#L558): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 576:1](https://github.com/statsmodels/statsmodels/blob/faa2b48553f2c50421507dca5d20a1bc624b3077/statsmodels/tsa/vector_ar/irf.py#L576): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 578:1](https://github.com/statsmodels/statsmodels/blob/faa2b48553f2c50421507dca5d20a1bc624b3077/statsmodels/tsa/vector_ar/irf.py#L578): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace

2021-04-02 14:26 UTC, jseabold commented on statsmodels/tsa/vector_ar/irf.py
> +        gamma_sort = np.sort(gamma, axis=0) #sort to get quapl)-1
This looks like an accident. Can you back this change out?

2021-04-02 17:47 UTC, jseabold requested changes
Overall this looks correct to me.

There's an accidental change that needs to be fixed, some style fixes, and a few nit-picky "optimizations."

2021-04-02 17:47 UTC, jseabold commented on statsmodels/tsa/vector_ar/irf.py
> +                     seed=None):
This change might need to wait since we already use the current pattern elsewhere.

2021-04-23 20:31 UTC, evivanov commented on statsmodels/tsa/vector_ar/irf.py
> +            e_hatb = resample(resid)
Unfortunately not
Residuals are not 1-dimensional and the choice function cannot work with that. Maybe there is another way but I am not aware of it

2021-04-23 20:38 UTC, evivanov commented
> Overall this looks correct to me.
> 
> There's an accidental change that needs to be fixed, some style fixes, and a few nit-picky "optimizations."

@jseabold, thank you for the comments! I have resolved most of the issues and added new commit

2023-08-07 09:19 UTC, closed without merging