ENH: Add pandas dataframe capability to variance_inflation_factor
statsmodels/statsmodels pull request #6780
Opened 2020-06-05 21:16 UTC by o-P-o

Proposing a small change to the variance_inflation_factor() method in the outliers_influence package, in order to allow `exog` input to be a pandas DataFrame as well as a numpy array.

In the test, the value computed for the VIF using my proposed code edit with a pandas dataframe input is 16.4394, which I compare to the value computed using the current state of the method, taking an array as input.

2020-06-05 21:16 UTC, pep8speaks commented
Hello @o-P-o! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:



* In the file [`statsmodels/stats/tests/test_outliers_influence.py`](https://github.com/statsmodels/statsmodels/blob/588f5494a48aa05b11dd0ba394223a9a9fca0743/statsmodels/stats/tests/test_outliers_influence.py):

> [Line 3:1](https://github.com/statsmodels/statsmodels/blob/588f5494a48aa05b11dd0ba394223a9a9fca0743/statsmodels/stats/tests/test_outliers_influence.py#L3): [F401](https://duckduckgo.com/?q=pep8%20F401) 'statsmodels.datasets.get_rdataset' imported but unused

2021-04-02 14:09 UTC, jseabold requested changes
@o-P-o Requested a few minor changes.

2021-04-02 14:09 UTC, jseabold commented on statsmodels/stats/outliers_influence.py
> +    if isinstance(exog, pd.DataFrame):
Instead of this check, could you add `np.asarray` here as you've done in the test? That way, a DataFrame and an array will pass through.

2021-04-02 14:09 UTC, jseabold commented on statsmodels/stats/tests/test_outliers_influence.py
> +    vif = variance_inflation_factor(X_arr, exog_idx)
You'll want `X_arr` here to be a DataFrame instead of an array to make sure your code changes are tested.

2021-09-09 08:10 UTC, closed without merging

2021-09-09 08:10 UTC, bashtage commented
Thanks.