DOC: copula in user guide and examples
statsmodels/statsmodels pull request #7607
Opened 2021-07-27 17:18 UTC by tupui

Follow up of #7408 which adds Copula.

This PR adds some documentation in the user guide and an example notebook.

2021-07-29 19:57 UTC, tupui commented
@bashtage it would be great if you could have a look. Might be good to have another pair of eyes on this topic. Thanks 🙏

2021-07-30 10:45 UTC, bashtage requested changes
One small grammar mistake.  I will merge once fixed. Thanks.

2021-07-30 10:45 UTC, bashtage commented on docs/source/distributions.rst
> +parameters. Copula are used to construct a multivariate joint distribution and
Copulas or perhaps Copulae

2021-07-30 11:17 UTC, tupui commented on docs/source/distributions.rst
> +parameters. Copula are used to construct a multivariate joint distribution and
```suggestion
parameters. Copulae are used to construct a multivariate joint distribution and
```

2021-07-30 11:18 UTC, tupui commented
Thank you @bashtage

2021-07-30 11:25 UTC, bashtage commented
Thanks.

2021-07-30 11:25 UTC, merged