Dm test implementation
statsmodels/statsmodels pull request #8385
Opened 2022-08-26 03:37 UTC by alekracicot

- [ ] closes #xxxx
- [ x] tests added / passed. 
- [x ] code/documentation is well formatted.  
- [x ] properly formatted commit message. See 
      [NumPy's guide](https://docs.scipy.org/doc/numpy-1.15.1/dev/gitwash/development_workflow.html#writing-the-commit-message). 

<details>
Related to issue #8374 

I found an implementation on this github https://github.com/johntwk/Diebold-Mariano-Test which I modified and adapted to the code base. It produces the same results has the R package. Tests are implemented, but I am not very familiar with unit tests and therefore they may not be well done. 

I am currently working on the multivariate version of the test (more then 2 forecasts).
**Notes**:

* It is essential that you add a test when making code changes. Tests are not 
  needed for doc changes.
* When adding a new function, test values should usually be verified in another package (e.g., R/SAS/Stata).
* When fixing a bug, you must add a test that would produce the bug in main and
  then show that it is fixed with the new code.
* New code additions must be well formatted. Changes should pass flake8. If on Linux or OSX, you can
  verify you changes are well formatted by running 
  ```
  git diff upstream/main -u -- "*.py" | flake8 --diff --isolated
  ```
  assuming `flake8` is installed. This command is also available on Windows 
  using the Windows System for Linux once `flake8` is installed in the 
  local Linux environment. While passing this test is not required, it is good practice and it help 
  improve code quality in `statsmodels`.
* Docstring additions must render correctly, including escapes and LaTeX.

</details>

2022-08-26 03:37 UTC, pep8speaks commented
Hello @alekracicot! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`statsmodels/tsa/stattools.py`](https://github.com/statsmodels/statsmodels/blob/7d2ddd845426faa1f1f6de977e3ad418e8accd4a/statsmodels/tsa/stattools.py):

> [Line 1899:61](https://github.com/statsmodels/statsmodels/blob/7d2ddd845426faa1f1f6de977e3ad418e8accd4a/statsmodels/tsa/stattools.py#L1899): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 1902:65](https://github.com/statsmodels/statsmodels/blob/7d2ddd845426faa1f1f6de977e3ad418e8accd4a/statsmodels/tsa/stattools.py#L1902): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 1914:55](https://github.com/statsmodels/statsmodels/blob/7d2ddd845426faa1f1f6de977e3ad418e8accd4a/statsmodels/tsa/stattools.py#L1914): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 1928:51](https://github.com/statsmodels/statsmodels/blob/7d2ddd845426faa1f1f6de977e3ad418e8accd4a/statsmodels/tsa/stattools.py#L1928): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 1933:78](https://github.com/statsmodels/statsmodels/blob/7d2ddd845426faa1f1f6de977e3ad418e8accd4a/statsmodels/tsa/stattools.py#L1933): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 1939:1](https://github.com/statsmodels/statsmodels/blob/7d2ddd845426faa1f1f6de977e3ad418e8accd4a/statsmodels/tsa/stattools.py#L1939): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 1944:1](https://github.com/statsmodels/statsmodels/blob/7d2ddd845426faa1f1f6de977e3ad418e8accd4a/statsmodels/tsa/stattools.py#L1944): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 1948:1](https://github.com/statsmodels/statsmodels/blob/7d2ddd845426faa1f1f6de977e3ad418e8accd4a/statsmodels/tsa/stattools.py#L1948): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 1952:1](https://github.com/statsmodels/statsmodels/blob/7d2ddd845426faa1f1f6de977e3ad418e8accd4a/statsmodels/tsa/stattools.py#L1952): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 1963:1](https://github.com/statsmodels/statsmodels/blob/7d2ddd845426faa1f1f6de977e3ad418e8accd4a/statsmodels/tsa/stattools.py#L1963): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 1973:1](https://github.com/statsmodels/statsmodels/blob/7d2ddd845426faa1f1f6de977e3ad418e8accd4a/statsmodels/tsa/stattools.py#L1973): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 1974:32](https://github.com/statsmodels/statsmodels/blob/7d2ddd845426faa1f1f6de977e3ad418e8accd4a/statsmodels/tsa/stattools.py#L1974): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 1979:1](https://github.com/statsmodels/statsmodels/blob/7d2ddd845426faa1f1f6de977e3ad418e8accd4a/statsmodels/tsa/stattools.py#L1979): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 1984:1](https://github.com/statsmodels/statsmodels/blob/7d2ddd845426faa1f1f6de977e3ad418e8accd4a/statsmodels/tsa/stattools.py#L1984): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 1987:41](https://github.com/statsmodels/statsmodels/blob/7d2ddd845426faa1f1f6de977e3ad418e8accd4a/statsmodels/tsa/stattools.py#L1987): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 1989:1](https://github.com/statsmodels/statsmodels/blob/7d2ddd845426faa1f1f6de977e3ad418e8accd4a/statsmodels/tsa/stattools.py#L1989): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace

* In the file [`statsmodels/tsa/tests/test_stattools.py`](https://github.com/statsmodels/statsmodels/blob/7d2ddd845426faa1f1f6de977e3ad418e8accd4a/statsmodels/tsa/tests/test_stattools.py):

> [Line 1100:96](https://github.com/statsmodels/statsmodels/blob/7d2ddd845426faa1f1f6de977e3ad418e8accd4a/statsmodels/tsa/tests/test_stattools.py#L1100): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 1101:97](https://github.com/statsmodels/statsmodels/blob/7d2ddd845426faa1f1f6de977e3ad418e8accd4a/statsmodels/tsa/tests/test_stattools.py#L1101): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 1102:96](https://github.com/statsmodels/statsmodels/blob/7d2ddd845426faa1f1f6de977e3ad418e8accd4a/statsmodels/tsa/tests/test_stattools.py#L1102): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 1104:97](https://github.com/statsmodels/statsmodels/blob/7d2ddd845426faa1f1f6de977e3ad418e8accd4a/statsmodels/tsa/tests/test_stattools.py#L1104): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 1105:95](https://github.com/statsmodels/statsmodels/blob/7d2ddd845426faa1f1f6de977e3ad418e8accd4a/statsmodels/tsa/tests/test_stattools.py#L1105): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 1106:97](https://github.com/statsmodels/statsmodels/blob/7d2ddd845426faa1f1f6de977e3ad418e8accd4a/statsmodels/tsa/tests/test_stattools.py#L1106): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 1109:95](https://github.com/statsmodels/statsmodels/blob/7d2ddd845426faa1f1f6de977e3ad418e8accd4a/statsmodels/tsa/tests/test_stattools.py#L1109): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 1110:95](https://github.com/statsmodels/statsmodels/blob/7d2ddd845426faa1f1f6de977e3ad418e8accd4a/statsmodels/tsa/tests/test_stattools.py#L1110): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace

2022-08-27 04:01 UTC, ChadFulton commented
Thank you for submitting this pull request.  I notice a couple of outstanding issues:

1. Given how closely this code follows / uses the reference implementation, I think we should at least reach out to the author to see if they are okay with this being included in Statsmodels.
2. At the very minimum, we need to include attribution, the copyright notice for John Tsang, and a note that this code is based on code licensed under MIT.
3. Thanks for writing unit tests. You should also include the code for the package that generated the results you are testing against (e.g. in R, Stata, Eviews, or whatever you used).
4. Statsmodels style is to include spaces around all operators other than `**`.  So instead of `x+y` we would have `x + y`.

2022-08-27 16:05 UTC, alekracicot commented
Hi, I will reach out to the author & implement de changes.

2022-08-29 20:12 UTC, alekracicot commented
> 3\. Thanks for writing unit tests. You should also include the code for the package that generated the results you are testing against (e.g. in R, Stata, Eviews, or whatever you used).

I reached out to the author and he is fine with including this to statsmodels. I also included the license. As for the code generating the results, should I add it to the docstring of the test? 

Best, 
Alek

2022-09-05 13:35 UTC, bashtage commented
I think we should make criterion flexible.  Specifically, it should accept either a string or a function with the signature `Callable[[ndarray, ndarray], ndarray]` where the inputs would be `y`, and either  `f1` or `f2`. It would then return `L(y, fj)` for j=1,2.  This would let the user provide other loss functions, but otherwise use the same function.

2022-09-05 13:40 UTC, bashtage requested changes
Would be a good idea to generalize a bit and to explain the precise intent of each input.

2022-09-05 13:40 UTC, bashtage commented on statsmodels/tsa/stattools.py
> +def diebold_mariano_test(y, forecast1, forecast2, horizon=1,
Need to have options for estimating the long-run variance of the loss differential.  When conducting DM tests it is necessary to allow for the possibility of a correlated sequence of loss differences.  Newey-west or something more general.

2022-09-05 13:40 UTC, bashtage commented on statsmodels/tsa/stattools.py
> +    horizon : int
Would be really good to have an example showing how horizon=2 is really used.  What alignment is assumed for Y and the forecasts? For example, if horizon=5, y[100] is observation 100 for y.  What is f1[100] and f1[105]?

2026-08-09 19:31 UTC, closed without merging