Feat/allow list of lags
statsmodels/statsmodels pull request #9000
Opened 2023-09-13 17:51 UTC by camaramm

- [ ] closes #xxxx (not applicable)
- [x] tests added / passed. 
- [x] code/documentation is well formatted.  
- [x] properly formatted commit message. See 
      [NumPy's guide](https://docs.scipy.org/doc/numpy-1.15.1/dev/gitwash/development_workflow.html#writing-the-commit-message). 

<details>

**Notes**:

* It is essential that you add a test when making code changes. Tests are not 
  needed for doc changes.
* When adding a new function, test values should usually be verified in another package (e.g., R/SAS/Stata).
* When fixing a bug, you must add a test that would produce the bug in main and
  then show that it is fixed with the new code.
* New code additions must be well formatted. Changes should pass flake8. If on Linux or OSX, you can
  verify you changes are well formatted by running 
  ```
  git diff upstream/main -u -- "*.py" | flake8 --diff --isolated
  ```
  assuming `flake8` is installed. This command is also available on Windows 
  using the Windows System for Linux once `flake8` is installed in the 
  local Linux environment. While passing this test is not required, it is good practice and it help 
  improve code quality in `statsmodels`.
* Docstring additions must render correctly, including escapes and LaTeX.

</details>

2023-09-15 11:48 UTC, bashtage commented
I think it would be better to not be so specific.  It should either be `int` or `array_like[int]`.  Then what you should do is 

```
if np.isscalar(lags):
   # Verify is a valid integer
else:
   # Convert to array, verify 1D, integer, all values valid (>0), and unique
```

2023-09-15 21:30 UTC, camaramm commented
Thanks, good suggestion.
Do you think checking if values are unique is a requirement or it can be flexible?

2025-08-12 14:22 UTC, camaramm commented
Hi, @bashtage . In the last commit, the checks for input argument were added as requested (https://github.com/statsmodels/statsmodels/pull/9000#issuecomment-1721144763). Can you check it?

2025-08-18 10:24 UTC, bashtage commented
@camaramm Looks good but needs a test verifying that this works for the new input types.

2026-07-24 11:26 UTC, bashtage commented
Hi, can you add a test that shows that this workd as expected?

2026-07-24 11:26 UTC, bashtage commented
Also need to sort out the rebase

2026-07-28 14:51 UTC, bashtage requested changes
Should be substantially simplified by consolidating the two paths into a single array-based one.

2026-07-28 14:51 UTC, bashtage commented on statsmodels/tsa/tsatools.py
> +        maxlag_array = array_like(maxlag, "maxlag")
set `maxdim=1, ndim=1` here, save a checks.

2026-07-28 14:51 UTC, bashtage commented on statsmodels/tsa/tsatools.py
> +        maxlag = [np.int32(lag) for lag in maxlag_array]
Just use `int`.

2026-07-28 14:51 UTC, bashtage commented on statsmodels/tsa/tsatools.py
> +    if isinstance(maxlag, int):
One you get here you might as well refedine `maxlag = np.arange(0, maxlag+1)` and then you only need a single path the rest of the code. Not need for `int` path, only array path.

2026-08-02 08:56 UTC, bashtage commented
I took your work and did the last few steps in #10016.  Thanks.

2026-08-02 15:13 UTC, closed without merging